export {
  applyImagesToShipRecords,
  areImageEntriesEqual,
  areManageShipCardsEqual,
  cloneManageItems,
  emptyManageShipCard,
  filterVessels,
  findImageEntryForRegistration,
  getExtensionFromFileName,
  getExtensionFromMimeType,
  getMimeTypeFromDataUrl,
  getVesselTypeFromBusiness,
  isPlaceholderImage,
  mergeImportedShipRecords,
  normalizeShipCardsForStorage,
  rebuildImageEntriesFromShips,
} from './domain/ships.js';
